# Generated by Django 5.2.10 on 2026-01-30 20:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_text_streamfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment this is a reply to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Programming language (e.g., python, javascript, html)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Your code here"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 1), ("code", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
