# Generated by Django 5.2.10 on 2026-02-02 12:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_parent_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Programming language (e.g., python, javascript, html)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Legacy code content", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Your code here"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 1), ("content", 2), ("code", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 4)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Programming language (e.g., python, javascript, html)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Legacy code content", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Your code here"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 1), ("content", 2), ("code", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
