# Generated by Django 5.2.10 on 2026-02-16 19:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpage_body_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Programming language (e.g., python, javascript, html)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Your code here"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 1), ("code", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 3)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Programming language (e.g., python, javascript, html)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Your code here"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 1), ("code", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
