# Generated by Django 5.2.15 on 2026-07-07 12:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_configure_wagtail_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('image', 4), ('video', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Programming language (e.g., python, javascript, html)', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Your code here'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blog/blocks/image_block.html'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube or Vimeo URL'})}),
        ),
    ]
